/**
 * Created by Reza on 03/04/2025.
 */

if (MINESWEEPER_DEFAULT_LOCALE === 'en') {
    LOCALIZATION_STRINGS = {
        GAME_NAME: 'Minesweeper',
        NEW_GAME: 'New Game',
        OPTIONS: 'Settings',
        STATISTICS: 'Statistics',
        HELP: 'Help',
        ABOUT: 'About',
        MESSAGE_WON: 'Congratulations, you won the game!<br/>',
        MESSAGE_LOST: 'Sorry, you lost this game. Better luck next time!<br/>',
        SAVED_AS: 'saved as',
        DIFFICULTY: 'Difficulty',
        DIFFICULTY_LEVELS: {
            beginner: 'Beginner',
            intermediate: 'Intermediate',
            advanced: 'Advanced',
            BEGINNER_HINT: 'Beginner - 10 Mines - 9 * 9 Grid',
            INTERMEDIATE_HINT: 'Intermediate - 40 Mines - 16 * 16 Grid',
            ADVANCED_HINT: 'Advanced - 99 Mines - 16 * 30 Grid',
        },
        HELP_CONTENT: 'Minesweeper is a deceptively simple test of memory and reasoning and one of the most popular Windows games\nof all time. The goal is to find the empty squares and avoid the mines. Sounds easy, right?',
        DEVELOPED_BY_CONTENT: 'Minesweeper HTML5 game developed by',
        FOR_FUN_CONTENT: 'for fun',
        WON_MESSAGE: 'You Won The Game.',
        YEAR_MESSAGE: 'Created with love in 2017',
        MAIN_MENU: 'Main Menu',
        SAVE: 'Save',
        SAVE_HINT: 'Your preferences will be reloaded even after you close your browser',
        GAME_LOST_TITLE: 'Game Lost',
        GAME_WON_TITLE: 'Game Won',
        BROWSER_INCOMPATIBLE_MESSAGE: 'Your browser is not compatible, please UPGRADE!',
        SECONDS: 'seconds',
        TIME: 'Time',
        BEST_TIME: 'Best time',
        GAMES_PLAYED: 'Games played',
        GAMES_WON: 'Games won',
        SAVING_NOT_SUPPORTED: 'Saving is not supported!',
        LOADING_NOT_SUPPORTED: 'Loading is not supported!',
    };
} else if (MINESWEEPER_DEFAULT_LOCALE === 'fa') {
    LOCALIZATION_STRINGS = {
        GAME_NAME: 'مین‎روب',
        NEW_GAME: 'بازی جدید',
        OPTIONS: 'تنظیمات',
        STATISTICS: 'آمار',
        HELP: 'راهنما',
        ABOUT: 'درباره',
        MESSAGE_WON: 'تبریک، شما برنده شدید!</br>',
        MESSAGE_LOST: 'متاسفانه بازنده شدید. دفعه دیگه خوش شانس باشی!</br>',
        SAVED_AS: 'ذخیره شد به عنوان',
        DIFFICULTY: 'درجه سختی',
        DIFFICULTY_LEVELS: {
            beginner: 'مبتدی',
            intermediate: 'متوسط',
            advanced: 'پیشرفته',
            BEGINNER_HINT: 'مبتدی - 10 مین - صفحه 9 * 9',
            INTERMEDIATE_HINT: 'متوسط - 40 مین - صفحه 16 * 16',
            ADVANCED_HINT: 'پیشرفته - 99 مین - صفحه 16 * 30',
        },
        HELP_CONTENT: 'مین‎روب یک آزمون فریبنده ساده برای حافظه و استدلال و یکی از محبوب ترین بازی های ویندوز است. تمام دوران هدف این است که مربع های خالی را پیدا کنید و از معادن اجتناب کنید. آسان به نظر می رسد، درست است؟',
        ABOUT_CONTENT: "توسعه توسط  برای تفریح.",
        DEVELOPED_BY_CONTENT: 'مین‎روب بر پایۀ HTML5 توسعه داده شده توسط',
        FOR_FUN_CONTENT: 'برای سرگرمی',
        YEAR_MESSAGE: "ساخته شده با عشق در 1396",
        MAIN_MENU: 'منو اصلی',
        SAVE: 'ذخیره',
        SAVE_HINT: 'تنظمات شما با بستن مرورگر هم حفظ می‎شود',
        GAME_LOST_TITLE: 'بازی باخته',
        GAME_WON_TITLE: 'بازی برده',
        BROWSER_INCOMPATIBLE_MESSAGE: 'مرورگر شما قدیمی است؛ لطفا به روز رسانی کنید!',
        SECONDS: 'ثانیه',
        TIME: 'زمان',
        BEST_TIME: 'بهترین زمان',
        GAMES_PLAYED: 'تعداد بازی',
        GAMES_WON: 'تعداد بازی برده',
        LOADING_NOT_SUPPORTED: 'بارگذاری پشتیبانی نمی‎شود',
    };
}
